version: "2"

linters:
  default: all
  disable:
    - depguard
    - revive
    - tagliatelle
  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - unnamedResult
    ireturn:
      allow:
        - error
        - generic
    wrapcheck:
      ignore-package-globs:
        - github\.com\/samber\/oops
  exclusions:
    rules:
      # simple rules for tests
      - path: _test\.go
        linters:
          - funlen
          - bodyclose

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/therenotomorrow/tmdb)
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    golines:
      max-len: 120
      tab-len: 4
      shorten-comments: true
      chain-split-dots: true

issues:
  fix: true
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  show-stats: true

run:
  go: "1.24"
  allow-parallel-runners: true
  timeout: 5m
