name: Setup Go and Just
description: Sets up Go and Just

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - uses: extractions/setup-just@v3
      with:
        just-version: '1.40.0'
