name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/just-go
      - name: Lint
        run: just lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/just-go
      - name: Test
        run: just test cover
      - name: Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
