name: CI

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - uses: extractions/setup-just@v3
        with:
          just-version: '1.40.0'
      - name: Lint
        run: just lint
